POST http://localhost:8080/auction

{
"product_name": "iphone",
"category": "eletronics",
"description": "auction 1 description",
"condition": 0
}

###

GET http://localhost:8080/auction?status=0

### 

GET http://localhost:8080/auction/winner/77f3d8d2-e418-46ee-b986-11284a91f234